name: cookie-ci

on: 
  push:
    branches:
      - "main"

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: test frontend
        run: go test
        working-directory: frontend     