name: cookie-ci
on: push 
jobs:
  test-frontend:
    name: Running test on frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check out repository
    - name: test frontend
      run: go test
      working-directory: frontend
  
  build frontend:
    name: Building the frontend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: build frontend
        run: docker build . -t dockerfile
        working-directory: frontend

  build backend:
    name: Building the backend
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: build backend
        run: docker build . -t dockerfile
        working-directory: backend  