name: cookie-ci
on: push 
jobs:
  Test-frontend:
    name: Running test on frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check out repository
    - name: test frontend
      run: go test
      working-directory: frontend   